---
apiVersion: v1
kind: Namespace
metadata:
  name: test-webhook
---
apiVersion: v1
kind: Secret
metadata:
  name: test-webhook
  namespace: test-webhook
type: opaque
data:
  tls.crt: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBcXJkRVpvNzk2WmtMREV0Si9TcWlwUUZUd251SnNXMUE5WWlHb2gwNmpiWHNGUU80Cnl1Y0FqMU9jamFhc1M1b0xmTGFVTTB6K3hCcHRKU0h3dTFMYURuVTMwZG44ZjdxMGF2aGRxSEFvdzZ1ZkMzdncKUmpKYTIrVmYxUDlnOU5oSUs5eVNQQi95enk5bGE0S0R5UVFxRUpOQVlJMmxpYkFNcG05cTR4bkVXNmJXRk9zSQpsNWhQUHF0WmEzSlROMHVsVExaRUZUbXZDNW0wdXRRSWVqNUdHWkRjOVRSUG51WTI3aEFIdkhJUjJPNFZpamlLClhudXk2WDlqcmZhc0daOEpQRXBoc0lLMXM2QXE3M1d1djI4R21kTlQ2MklQT0pzcFVmR0NjVE1SUVZlclI5eFcKbFRHaUg5T3VRcWxGRzN1UEY3dS92d014Mmd1WmgxeFFRSklXRVFJREFRQUJBb0lCQUhJcCt3a202UEMxMHlpVwpsTlZFRk42SjQ2eTBsdUZiY2N5QlQ1L01NaU1nbk05MDNMaDhBT2pZZm1KUUt2cW4rclNkR01DeDVkSFk1bEtsCnZ1cFd2dEphVzBqd0lTWitBamRpL3FjczBtWUFPRzBpcGcwYmtaMXFhRXIxdWE0amtTZ2I2b05neml6MXdqcEMKWHNVb0RzVms0L0Z0NkYwS3FYc0lHWS9qNUdkeE0rZkxyNzM2Sk4rK09pRWlaeEsxZkFlS1JsOWs5NXRSUnJLdQpKcnZBMmRRTGhMNTd3S0Q5ZHlOS0daL3B3WlRHYUZiL08zdGUvbVhrVWtJZXJkZlJ5Z1h2N1RJN0VBc0p5OEROCiszTlloRW5YQk9oU1V6Y2xGNHRwQ3hwdnViNE1QTm54TGVoUk5LT0J5VHFXSU0xWXk1bkhIWDNod1lmQjZDckoKWjA5YitOMENnWUVBMnFadUdON3U4Q1BFbjd5SmRKaVFzd1c3aVZUSlRVT3B2RXlBck5FTDArRFJUb0F2dXNoWApJbGI3aXhEUzZrdTZrUlVRQWlmall1bUlmSFRyVnNsM3l0U0Yzc25BTEJrWlZOSHRjdVlaTWswdHpSR0dMaS9WClhHNHpoTjhJNnNURU1RcDRkcEZWNDQyaHd4OHA4dE5KcHBDSVRlTHBIZmswRm93ODBaZnFVU01DZ1lFQXgrQ3MKVlkxU0tmMy9xWFJVM1ludE9vQy9JSDZvNngzTmplWjlsODFNTzBCUS9aaTd6azRKL3JYcy9Wbk84Q09yVmhJYgpUSkRXZ3FrcXFTYjNYbEUyY3Y2ckN3dkVsZzV0Zml4aHhMR0hMVzFwNDk2S3lnRjJyWStENURZejNuUjAvajRzCk5EWmF2TEVna21SVS9vTG1uY0NUQ2hkL3dnanpVT0lhSUUxaXdUc0NnWUFJS2ZTc2F3NkMydU1KajlHV0QrZy8KTnZTVW9SelBETHEydENpTnkxUmt1ZDAyMENSNEZlamkrRnAyQzgvRVBjV2VpeW5JMnRKcnJBcVRrdzRDZEkxTApmbm50SXAxUlNES2c3eUd0aTVmZlAvQjQyckdtNGRSV21pckVTRXVkOEhEZTMrUTFrU0dpMkhQMHhDSWQxZlBICkMxaDdpQUJxUlJiRHpNS3NsTDZEL3dLQmdBdWdRZVhvQm5OeTFzQWdpQjhxdXFYQWYxMkFnSXJNZlB4WC84NG8KbnRxRGJ6S1JBN3VJUm9TT1NHNmtIcWxSS2RJajAzcXNvZzJQa1crdFdJNGY0eTdsS1VYSE5YUVUrc0Z3QzIvSgpjN2RzdWRBTFRiOWFQbkR4L0JYMklTWTdWK0xCOHdoR2NSaXdwTmhmQmFLWU1wblNiYnNVaXRYYWQyeW8raVFPCjNFT3BBb0dBR1Z0RHVTcFkyenFDem0vSEtDaXE2aTJGbXJsQWViSnBhMFBpaGd5MHN5L1VEdFpjVEYxSFEwbkEKTngvV2tDMGxKVExOSmhGVWdpdjZWaVkyL3c0bEswUS93WDZGUmR1MlFEQmFQQ25uS05lT3FmVml6Uk10M3hnOQptNm1YVWRTVm1Hbk05REpweXcxNFQ0K0tQRzNmMnF2ejUxL3FINVpveWJWZnVqNXBteHc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0VENDQVowQ0NRQ21ZUGQ4YllKWDJEQU5CZ2txaGtpRzl3MEJBUXNGQURBVU1SSXdFQVlEVlFRRERBbDMKWldKb2IyOHVZMkV3SUJjTk1qRXdOREF4TVRnek5qTTFXaGdQTWpFeU1UQXpNRGd4T0RNMk16VmFNQ014SVRBZgpCZ05WQkFNTUdIZGxZbWh2YjJzdWRHVnpkQzEzWldKb2IyOXJMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtxM1JHYU8vZW1aQ3d4TFNmMHFvcVVCVThKN2liRnRRUFdJaHFJZE9vMjEKN0JVRHVNcm5BSTlUbkkybXJFdWFDM3kybEROTS9zUWFiU1VoOEx0UzJnNTFOOUhaL0grNnRHcjRYYWh3S01Pcgpud3Q3OEVZeVd0dmxYOVQvWVBUWVNDdmNrandmOHM4dlpXdUNnOGtFS2hDVFFHQ05wWW13REtadmF1TVp4RnVtCjFoVHJDSmVZVHo2cldXdHlVemRMcFV5MlJCVTVyd3VadExyVUNIbytSaG1RM1BVMFQ1N21OdTRRQjd4eUVkanUKRllvNGlsNTdzdWwvWTYzMnJCbWZDVHhLWWJDQ3RiT2dLdTkxcnI5dkJwblRVK3RpRHppYktWSHhnbkV6RVVGWApxMGZjVnBVeG9oL1Rya0twUlJ0N2p4ZTd2NzhETWRvTG1ZZGNVRUNTRmhFQ0F3RUFBVEFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQWdFQVdhUmFkVE1laU83V0ZLa1lhT2prVlZCUGRTLzlGeHM4YXVBR2lWaWdNbVp3YXpPWFdvM2kKNEFUcEM0SlVLNERocGd6enRwSjczZEJWREFpRDA2ZXFuSDNveWJXTDdpU256aTJqYjcxRGEzOTYxMWdETHl2LwpXblFxa1owU1FGckNmVXhuNCsyOVRObXY4c3lmaFJ1cks0UUt1dVEyN29pSE1odU11N0R3bWUzT1htczR2aTNVClQ5THVVckwxMzVsMGlTendUYVk5dzVteWpVQXVrdkhDeGRveHlMQVY3eVJqZnN4NXdaeDcrQVJ5VkZGQ1R0Q0wKNm9EV2tqZTU3dEtDSTl1anVCcnFOQnpLa2dvNDA2ak15YW5oS0tPMGpkWnZHczEwL3VFWFZDK3hEdThYTXVMRgpGU21iUkY1OGZ6Z2ZTQ2JMSE9wc0FhMUZRUFM0VkxYWDVENkNZaHdicEVacWxudTNPNzA3MnlGZ3pGUXV3b09pCm1nREdtaGoyeVZPZTRKVlhoNTVOWC93QXhKdW53cS9DNzE3ajh4Y09nY3VNY21kRzQ3MHhYblRNTzJRN3ExYjMKZ3EvYngxaWw0ODBjRUU4ZGp0VmZKK3g2VFc5S3FraDgraWtrWUVIcy9yMXFzN0VDRDR0OUdqSTVqMWJTbm8rWQo3M1duV2VzUGt4NGNxMi80dEFocU1qQ1VVdUoxbW5HTlZXbzRqZjJtZmlqSGpONEdtKy9BWVRoMjdSaXJYTlZ4CnJkTGltaks4MFZGaWFESHhxK1J0c1ZQMC8zczhJdVpFZ2FDZDZHcC9jdk1zZlNNT0ZlQ2tJZkZVNlhGcFo0eGUKeThjWi93c0prUWZCWklqbnR2dS9rS252WVRyWDhVbEdTZ0VTcDNhbVN5K3R4NGJVY2dwc090RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webhook
  namespace: test-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sample-webhook"
      webhook: "true"
  template:
    metadata:
      labels:
        app: "sample-webhook"
        webhook: "true"
    spec:
      containers:
        - args:
            - --tls-cert-file=/webhook.local.config/certificates/tls.crt
            - --tls-private-key-file=/webhook.local.config/certificates/tls.key
            - --alsologtostderr
            - -v=4
            - 2>&1
          image: ypelud/test-mutating-webhook:latest
          imagePullPolicy: Never
          name: test-webhook
          ports:
            - containerPort: 443
              name: https
          resources: {}
          volumeMounts:
            - mountPath: /webhook.local.config/certificates
              name: webhook-certs
      volumes:
        - name: webhook-certs
          secret:
            secretName: test-webhook
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
  name: test-webhook
  namespace: test-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: "sample-webhook"
    webhook: "true"
  type: ClusterIP
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: test-webhook
webhooks:
  - admissionReviewVersions: [ "v1", "v1beta1"]
    clientConfig:
      service:
        name: test-webhook
        namespace: test-webhook
        path: /add-label
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVwakNDQW80Q0NRQ1BYSjBLRXNTckVEQU5CZ2txaGtpRzl3MEJBUXNGQURBVU1SSXdFQVlEVlFRRERBbDMKWldKb2IyOHVZMkV3SUJjTk1qRXdOREF4TVRnek5qTTFXaGdQTWpFeE9EQTVNakF4T0RNMk16VmFNQlF4RWpBUQpCZ05WQkFNTUNYZGxZbWh2Ynk1allUQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCCkFNUzNHOWp2Qks4MVpqMzNmemZhSmZqTnprQktVTVIzNTF4MmJROEdSeDc5elZVV3JLaXI3eHk3bDIySVgya1kKZFJ4ZmNBNEVBMGsvYXQ3RVpqN1RNZVlmd1N0OWFseldQOGdzQXJWWWdJRjJSRnpOVTV2SUxYY3crelNLVDZoRgpmZTZZZUFUSitrTWRXbkE3ZHFjNjViRStIaTBDYVRJMVp4M1FZTFJLMmFnbFZBVUdlblVNL0RmWGRNQmpvSTllClZXTjdwc2FQYU5WeHJ0RlhkbldNVGh0c21lN0hGQkxJeHB0QmZCeWROcktjNWlzWmloN2ZQN0lxODJGcDhrOWcKQjRCL3R4UjRCRkxVaUwrbUl2Q0tMMDFQbzJTM0NkY2hNbnl5cmV1TFA0aUkrZFBzaE5iRklPVS9lWmE1b1ZVSApUbURmL2JSVVF6TW9vcW8zQ21SWHRWa2p3UExyUjBEdkJrMUtVcGUwVW51eU4rMVNPRzNNMWNkM1pRcC9PQUJYCmtlMHorcVpaU29OVnhHNFNkTU40QmQxaG0vQnpOUHNVaVRxczhHZnl6cCtxOGY5Z0VPWFphYnVSSFJqOXpjMnMKRlVRQmlYWXhUelZkVFdSYWtLWEhENCtqaUNZY0M0Nm8xSFg4czFiN1NqbXYrdmZRMHh6VTNDU3djSGNTY1htWQpEbk1DRXFaemhHT0NMbGtWYWxQRDBjakxGQ2hGRVR4RXE2TnF6azlWeFp6RlpNUGpva1kzQ0Y1ckJmQitYeU1iCm5TYTkzZ20yUzNncEZkS1JZVFVWK3oyVXYySW5seDdlanVWbGFXbS9Ecjg5YlpLK1RQSVQwQUVCc1FzV2JEUjAKS0VlNFhMN2xBNEZYKy8xZzhaZ0gzOGt2U1dpSDQ1WlJ5OXNWMUcrOXBMQ0hBZ01CQUFFd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnSUJBS3c2RHZxaVlxeTZ2ZWwwd3pUWXVGSWRlaDhmU3d5U2s4eWFBM0kxeEN6NW1xb3M4dDU2CmRoM2V5YTl3QVBuSFlHdVFhMysxU2dIZHQ0ZGFCcnFzckEydGNMa1ppRk5rQ0ZQQkd2RFBUeS9KSUFqcVYvUnAKN0hrRGpFbVZPVGdCajd5QjQ1ejM1RW1ZN3VZcGlRRi9ndXFjb1pYWGE5VEdCenZjdms3MVp3TlZSTElBd1djcwpGM01WNFhiUDJvU1dsaVZsRnJSK2Q1NjM4aHpUdDc0MnJQblVrOEhxcDAvQkJSYWZ6azI3NldqWCtIZHhCb2lKCjJrSXdGSng1dGhFcWJ5MmMvaVRzbUVVdjgzWUlKQTIrSUg3WmVjZFNZcUdhaTROOTNMcE9PWUIxSmwxZ1hpbm8KVmEwS0FZd1NuRVFqUUd2V2tFMGJ2RWNMS0NHcXViOTQzZWFyNitLdjJtaDBhVllHMXY5UzdZeDVOSG9WTkUwZwpObXR5YUJUSDRrQTBlckJzZmE0UlZaYVZzMjhGNFdpU0pQTTQzaWpZeTAzbkphTlh4dDRjM1NERjVkZkJicGxBCmcwbE82ZlovMFhZN05WVkpwRDloaGtaM01OSTNEMndFRTFSUVFSdjg5eHFEV0JyK3kvY0hzTTFqQUxCZmJNclkKL2svR3RWbHZvVmxuN3dYTWxzUVdIVjBJVXBjeHQ2b0RDMGIzWGdSMzdzc1ppY2pNWFo1OEdaZENEbjg2L0tpVApudHVGbk1XVk1HS1pvUEx5OUQ4SmxNWGM3RTV5V2V3SklKY1NGYm5ZT0p2L05JZ2N6N04xRzFSbEhWOGN4anBiCktlUTQ1WERVaVErOW1DWWJ6T2xtNHBXbXdwVXJPb3JUaEV0blAzMXplUy8wUFVGUFVtRnFqcDBECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    failurePolicy: Fail
    name: webhook.test-webhook.com
    rules:
      - apiGroups: [ "*" ]
        apiVersions: ["*"]
        operations: [ "CREATE","UPDATE" ]
        resources: [ "*/*" ]
    sideEffects: None
    timeoutSeconds: 10